name: Build EXE

on:
  push:
    branches:
      - main   # or any branch you want to automate

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Choose the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole app.py  # Customize with your app's main file name
        # --noconsole removes the console window if you don't want it

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: KeybowApp
        path: dist/app.exe  # Path to your generated EXE

    - name: Clean up
      run: |
        del /f /q dist\*  # Delete the generated EXE from the runner to avoid clutter
