jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          python -m ensurepip --upgrade  # Ensure pip and setuptools are installed properly
          python -m tkinter  # Ensure tkinter is available

      - name: Build the application
        run: |
          pyinstaller --onefile keybow.py

      - name: Upload the built .exe as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: keybow-executable
          path: dist/keybow.exe  # Adjust path if necessary
